version: "3.7"
services:
    app:
        build:
            args:
                user: misha
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: marketplace-php
        container_name: marketplace-laravel
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - marketplace
    db:
        image: mysql:5.7
        container_name: mysql-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: marketplace
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_PASSWORD: 12345
            MYSQL_USER: admin
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - marketplace
    nginx:
        image: nginx:1.17-alpine
        container_name: marketplace-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - marketplace

networks:
    marketplace:
        driver: bridge
